blank_issues_enabled: false
contact_links:
  - name: 🔥 Feature Requests
    url: https://github.com/simpleclub/firebase-rules-helper/discussions/categories/ideas
    about: If you have an idea for improvements to a package or ideas for an additional one, please use Github Discusssions.
