nodeLinker: node-modules

npmMinimalAgeGate: '3d'

# The majority of NPM supply chain attacks are conducted via running scripts after installation.
# Most packages don't need to be running any scripts, so we should be disabling this by default.
# If a package needs to be running scripts, you can enable scripts for this package again:
# In the package.json specify a `dependenciesMeta` with the package as the key and a flag `built: true`.
# {
#   ...,
#   "dependencies": {...},
#   "dependenciesMeta": {
#     "<package>": {
#       "built": true
#     }
#   }
# }
enableScripts: false
