name: Publish new package version
on:
  release:
    types: [created]
jobs:
  build:
    if: ${{ startsWith(github.event.release.tag_name, '@simpleclub/') }}
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Set working directory for the package
        # the idea is that you take a "tag name" from the release
        # it should have a format of "@simpleclub/packagename@v0.0.0"
        # where "packagename" is a directory name under "packages"
        # 1. take the tag name -> github.event.release.tag_name
        # 2. parse it with 'sed' to extract the package name
        # 3. prepend the workdir with "packages/"
        # 4. push it into GITHUB_ENV so it can be access via {{ env.* }}
        run: echo "workdir=$(echo ${{ github.event.release.tag_name }} | sed 's/[a-z@]*\///' | sed 's/@.*//')" >> $GITHUB_ENV

      # Publish to NPM
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --cwd ${{ env.workdir }} --frozen-lockfile

      - name: Publish package to NPM
        run: yarn --cwd ${{ env.workdir }} release
        env:
          # NODE_AUTH_TOKEN is a special env variable that is written to .npmrc file
          # by `actions/setup-node@v1`
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Publish to Github packages
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Publish package to GitHub packages
        run: yarn --cwd ${{ env.workdir }} release
        env:
          # NODE_AUTH_TOKEN is a special env variable that is written to .npmrc file
          # by `actions/setup-node@v1`
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
